### ISSUE TITLE
Can this gem be used to implement IdP initiated SSO?

### ISSUE THREAD

**Issue by kaoru** [saml-idp/saml_idp#101]
Hey,

I'm trying to implement IdP initiated SSO where my rails app will be the identity provider.

I've already sent a list of users over to the service provider who should be allowed access. What I need to do now is allow a logged in user in our app to click a button and POST a blob of XML to the service provider's ACS endpoint, without having received an authn request from the service provider first.

I think this gem should be able to do that, but I just can't figure it out 😅 Can somebody help me out?

Thanks 💙

**Comment by billr578** [comment]
Did you ever get a response to this?  I'm trying to figure out the same thing.  Thanks!

**Comment by kaoru** [comment]
Hey @billr578,

I didn't get a response, but I did figure it out! We're using `saml_idp` to do IdP initiated SSO in production 👍 Our config looks like this:

```
SamlIdp.configure do |config|
  config.entity_id = 'https://www.charliehr.com'
  config.base_saml_location = config.entity_id

  config.name_id.formats = {
    persistent: ->(principal) { principal.saml_subject },
  }

  config.x509_certificate = ENV['SAML_X509_CERTIFICATE']
  config.secret_key = ENV['SAML_SECRET_KEY']
end
```

Where `User#saml_subject` is a method we've defined, it returns a string that matches the user ID we send in the daily CSV we send to our SSO partner.

When the user wants to log in via SSO we submit a form with two hidden fields: `SAMLResponse` and `RelayState`.

The `SAMLResponse` is:

```
SamlIdp::SamlResponse.new(
  UUID.generate,                                           # reference_id
  UUID.generate,                                           # response_id
  SamlIdp.config.base_saml_location,                       # opt_issuer_uri
  @user,                                                   # principal
  METADATA_URL',                                           # audience_uri
  nil,                                                     # saml_request_id
  ACS_URL,                                                 # acs_uri
  OpenSSL::Digest::SHA256,                                 # algorithm
  Saml::XML::Namespaces::AuthnContext::ClassRef::PASSWORD, # authn_context_classref
  3600,                                                    # expiry
  encryption_options,                                      # encryption options
  nil                                                      # session expiry
)
```

Encryption Options are:

```
{
  cert: CERT, # note this is *not* ENV['SAML_X509_CERTIFICATE']
  block_encryption: 'aes128-cbc',
  key_transport: 'rsa-1_5',
}
```

`SamlIdp::SamlResponse.new` returns an object with a method `#build` which returns a Base64 encoded string, and that's what we submit in the form.

`RelayState` is just a hard-coded URL which is the domain of the place where we submit the form, without the path.

Of course all of this might be completely custom to our one SSO partner - I have no idea how much of this is standard across most of SAML/SSO-land and how much is specific to us.

**Comment by jphenow** [comment]
Triaging old issues. Marking as enhancement so we can at least update README to better outline this scenario.

**Comment by adampal** [comment]
@kaoru, in your answer you note that the cert option in the encryption is *not* the ENV['SAML_X509_CERTIFICATE'].  Just wondering what certificate that is?
I'm getting a `cannot load such file -- xmlenc` error.  The default config seems to be:
`cert: saml_request.service_provider.cert`
but `saml_request.service_provider.cert` is nil for me so I'm not sure if I'm missing something else?
Thanks!

**Comment by kaoru** [comment]
Hey @adampal,

To be honest I'm not 100% sure any more. The company we were integrating with sent us two certificates, one of which we put into the `SamlResponse`'s encryption options, and the other we put into the SamlIdp `x509_certificate` config option.

Looking at the values I can only tell you that the `x509_certificate` one starts with `-----BEGIN CERTIFICATE-----\n` and ends with `\n-----END CERTIFICATE-----` and the other one doesn't - it just has the long base64 encoded certificate string. They're different from each other, and different from the config `secret_key` as well.

I can also tell you that _none_ of them are the certificate from the `<ds:X509Certificate>` tag in the metadata file.

Hope that helps and you figure it out (or better yet, already figured it out in the last 24 days 😅)

**Comment by adampal** [comment]
Thanks @kaoru.  I did figure it out in the end but to be honest now I don't actually remember what it was either!
I think it ended up being that the company we were integrating with weren't set up to encrypt the SAML response so just removing the encryption options from the controller method got it working...I think...

**Comment by Zogoo** [comment]
@kaoru, @adampal  I hope you guys could resolve your issue. 
I'm going to close this issue. And if you think this GEM has an issue or bug, please feel free re-open this issue or create a new one with a description that help to us identify issues.
If you need more questions about your issue or how to use it, it would be nice to have a message in our Gitter room
https://gitter.im/saml_idp/community?source=orgpage#
