### ISSUE TITLE
Update build matrix

### ISSUE THREAD

**Issue by jphenow** [saml-idp/saml_idp#106]
We're building against some very old ruby and rails. let's reduce the footprint to at least what's still commonly supported

**Comment by Zogoo** [comment]
@jphenow  
I tried reduce failure of build with my pull request. https://github.com/saml-idp/saml_idp/pull/109#discussion_r250104908. But still there 2 failures which not easy to fix it.

I think @tknzk already start to take action for this issue.
https://github.com/saml-idp/saml_idp/pull/110

**Comment by tknzk** [comment]
opened new pr https://github.com/saml-idp/saml_idp/pull/123
