### ISSUE TITLE
IncomingMetadata does't return entity id

### ISSUE THREAD

**Issue by Zogoo** [saml-idp/saml_idp#107]
Entity ID from SP metadata will help easier to identify SP information.
When dynamically register new SP to DB, it's required to identify that SP with entity id.
Of course we can do following trick, i would like to have inside of IncomingMetadata
`
 hash = SamlIdp::IncomingMetadata.new(raw_metadata)

 entity_id = hash.document.xpath('//md:EntityDescriptor/@entityID').first.value

 hash[:entity_id] = entity_id

`

I have fixed this issue in this pull request: https://github.com/saml-idp/saml_idp/pull/109

**Comment by jphenow** [comment]
Released in v0.9.0
