### ISSUE TITLE
Possible to use without a metadata_url for SP?

### ISSUE THREAD

**Issue by jackiejohnston** [saml-idp/saml_idp#115]
@jphenow @mvastola Is it possible to use this gem if your SP does not have a metadata URL, but provides you with a metadata xml code block?

**Comment by jphenow** [comment]
Hey @jackiejohnston sorry for the several months wait. If you somehow recall this and have an example, could you provide? Would help with outlining an enhancement you or someone could pick up.

**Comment by jackiejohnston** [comment]
@jphenow Our workaround was to turn the XML code block they provided into an XML file that we hosted ourselves then used that for the URL.
