### ISSUE TITLE
Consider a move to Github Actions

### ISSUE THREAD

**Issue by jphenow** [saml-idp/saml_idp#126]
It's taken about 30 minutes for travis to pick up a build much less run the matrix. Worth considering trying to move to Github actions if only to have a more first-party integration.

**Comment by mjobin-mdsol** [comment]
travis is working fine at the moment, I would not bother making the change

**Comment by jphenow** [comment]
https://github.com/saml-idp/saml_idp/pull/158 makes this change for due to capacity from Travis going down. Could have moved to travis-ci.com but now felt like a good time to bring it into the GitHub ecosystem. If others feel very strongly, I'm fine opening that conversation.

Leaving this ticket open because I'd like to add an action that cuts the new gem on master merge.

**Comment by Zogoo** [comment]
In my opinion If we could manage things with in one place (Github), that would be the best option.
@jphenow I think you may want to drop Travis resources since we could confirm that Github actions is working fine.
https://github.com/saml-idp/saml_idp/actions/runs/472242466

**Comment by jphenow** [comment]
Sounds good - Travis should be "off" now, but it will be more obvious as folks create new PRs. 

I'll leave this up while we confirm that and once I figure out how we'd have the gem-push part of the automation.

**Comment by mjobin-mdsol** [comment]
this is done, I guess we can close
