### ISSUE TITLE
cannot load such file -- xmlenc

### ISSUE THREAD

**Issue by TimFung93** [saml-idp/saml_idp#127]
I am trying to encrypt my response by calling 
```
encode_response(user, encryption: {
        block_encryption: 'aes256-cbc',
        key_transport: 'rsa-oaep-mgf1p'
})
```
but I keep getting `cannot load such file -- xmlenc`. Has anyone else gotten this issue?

**Comment by TimFung93** [comment]
Ahh i see I found in the `saml_idp.gemspec` it is added as a dev dependency but not a dependency.

**Comment by mjobin-mdsol** [comment]
it was added as an optional dependency on purpose.
those who need it for now can add to their Gemfile.
if enough people advocate we make it required, we will consider. 
for now, i am not seeing anyone else who has reported it

**Comment by kwerle** [comment]
I ran into this, too.  It'd be super nice to catch this at a high level, report the fix (add the gem) and reraise it.
