### ISSUE TITLE
Do I need to regenerate Metadata and share to SP to updating session_expiry?

### ISSUE THREAD

**Issue by RohitVenturit** [saml-idp/saml_idp#130]
Hello, I wanted session should not expire, so I have updated config.session_expiry = 0 , do I need to regenerate Metadata and share to SP to take effect ?

**Comment by RohitVenturit** [comment]
Can anyone reply who has idea about it. Please feel free to comments.

**Comment by Zogoo** [comment]
@RohitVenturit if I understand correctly, you wanted control SP session time via SAML response? For that I think your SP should support that `SessionNotOnOrAfter` field of SAML response message's Assertion part. As IdP if you set 0, field will be removed from the SAML response as optional fields.
If you interested more about it please take a look at line 1061 of [SAML 2.0 core doc](http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf)

**Comment by Zogoo** [comment]
@RohitVenturit If you happy to my answer or if you still want to ask more you may want to ask it on our "gitter" room.
https://gitter.im/saml_idp/community
Or you if you realized some issue regarding your question, please feel free reopen this issue or create new one.
