### ISSUE TITLE
How to write automated tests for verify our implementation?

### ISSUE THREAD

**Issue by mjobin-mdsol** [saml-idp/saml_idp#133]
After integrating this gem into our existing login service.
is there some automated tests gabarit we could be following to make sure our implementation is working before deploying?

any insights here would be helpful.

thank you

**Comment by Zogoo** [comment]
@mjobin-mdsol  I think the original plan was the nested  project that uses `ruby-saml` gem which act as SP. But I think the internal rails app version get old and I think it's not efficient to manage another app inside of gem resources.
So, I would suggest that keep RSPEC test and only we might need to ask contributes provide test close to real life usage logic.

**Comment by mjobin-mdsol** [comment]
instead of storing the rails app inside, it should be built from scratch on each tests run.
some of the cucumber gems does that
now that we only support 5.2 and 6.0
it should be easier.
but I see how it is some task for someone to get through

**Comment by mjobin-mdsol** [comment]
wait, we moved the conversation to test within this gem
but I was more asking about tests in the app that use this gem.
what kind of test a user of this gem could add to ensure its implementation is correct?

**Comment by Zogoo** [comment]
@mjobin-mdsol if you are talking about Rails app side test. 
Then I would suggest to use https://github.com/onelogin/ruby-saml gem to create the request test. One login community guys are specialized for SSO protocols. 
You may already realize they also have tools can you confirm SAML protocols https://www.samltool.com/online_tools.php

I know you already there, if someone who may have more questions about app side implementation, I would suggest to ask it our https://gitter.im/saml_idp channel.

**Comment by Zogoo** [comment]
@mjobin-mdsol if you happy my answer or you want to discuss. We may can continue discuss it on our "gitter" room https://gitter.im/saml_idp/community.
Or if you realized the different issue that you still want to dicsuss, I would suggest to reopen this issue or create new one.
