### ISSUE TITLE
How can we help the maintainers?

### ISSUE THREAD

**Issue by mjobin-mdsol** [saml-idp/saml_idp#137]
several pull requests seems ready.

even one was planned for a release earlier this year.

we are a few people ready to help.

I am thinking @Zogoo as the SAML expert and I can help with release coordination.

can @jphenow find sometime to review open requests and cut a release? or can you give github+rubygems write access to someone ? 

thank you

**Comment by mjobin-mdsol** [comment]
NOTE we have setup a Chat room at https://gitter.im/saml_idp/community

**Comment by jphenow** [comment]
I'll jump into gitter sometime soon - I'm on call at work for a few weeks so my focus is elsewhere. I've given @Zogoo write access for the repo, and you triage access for now. Once we get some things done, I can look at adding one or both of you to rubygem access.

**Comment by jphenow** [comment]
also v0.11.0 has been released with the ready PRs

**Comment by mjobin-mdsol** [comment]
Awesome ! Thank you
