### ISSUE TITLE
clarify how to configure SP

### ISSUE THREAD

**Issue by mjobin-mdsol** [saml-idp/saml_idp#140]
Hi,

README shows that we can configure SP as simply as specifying a metadata_url 

```
  service_providers = {
    "some-issuer-url.com/saml" => {
      fingerprint: "9E:65:2E:03:06:8D:80:F2:86:C7:6C:77:A1:D9:14:97:0A:4D:F4:4D",
      metadata_url: "http://some-issuer-url.com/saml/metadata",
      response_hosts: ["foo.some-issuer-url.com"]
    },
  }
```

but I can't find where the `acs_url` and `cert` is being fetch from that metadata url ...
is that really enough configuration ? or is it outdated?

**Comment by Zogoo** [comment]
@mjobin-mdsol  I think this part of config showing an example that SP and IdP are trusted services and they shared metadata with trusted endpoint.
Most likely this will happen some internal network services that authenticate with internal SAML IdP. Because this is they don't want to upload SP metadata to each time they update.
But, over the internet it this will be a dangerous way to upload metadata to the IdP unless the metadata signed and somehow each service has keys that confirm signatures.

**Comment by mjobin-mdsol** [comment]
really, I don't get it...
this snippet is the example I took from the README
but the code does not seems to be doing anything with the metadata?

I wonder how many used this gem for an actual SAML Idp running in production?

**Comment by Zogoo** [comment]
@mjobin-mdsol  you may want to check
lib/saml_idp/service_provider.rb:77
lib/saml_idp/incoming_metadata.rb

If you specify metadata URL it suppose to download from that URL. For security reason, I will never suggest to use this feature for 3rd party SP service.

**Comment by mjobin-mdsol** [comment]
thanks.
I was expecting to see something about `acs_url` inside `lib/saml_idp/incoming_metadata.rb`
that's why I got confused.

**Comment by mjobin-mdsol** [comment]
We have SP configuration in database and this is out we are doing it right now.

```ruby
  def self.fetch_saml_service_provider_config_for(issuer_or_entity_id)
    sp_app = App.saml_sps.where(sso_service_url: issuer_or_entity_id).first
    return {} unless sp_app

    sp_acs_url = sp_app.idp_homepage_url
    sp_x509_cert = sp_app.idp_certificate
    {
      fingerprint: SamlIdp::Fingerprint.certificate_digest(sp_x509_cert),
      # metadata_url: # only acs_url and cert should be required,
      acs_url: sp_acs_url,
      cert: sp_x509_cert,
      response_hosts: URI.parse(sp_app.base_url).host
    }
  end
```

I had no success with `metadata_url`
