### ISSUE TITLE
move to travis .com

### ISSUE THREAD

**Issue by mjobin-mdsol** [saml-idp/saml_idp#145]
travis-ci .org is going away and is running at reduced capacity.
you might have heard several discussion on twitter about that.

.com now supports opensource projects and we are invited to migrate

https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by Zogoo** [comment]
@jphenow I think this issue needs to be solved by you.

**Comment by jphenow** [comment]
Yep. Solved [here](https://github.com/saml-idp/saml_idp/issues/126)/[here](https://github.com/saml-idp/saml_idp/pull/159). Seemed like a reasonable time to cut over to github actions; partly because I'd like to add automation around cutting a new gem.
