### ISSUE TITLE
Question on configuring SP

### ISSUE THREAD

**Issue by linda-le1** [saml-idp/saml_idp#152]
Hello! I'm very new to SAML and am using this gem to turn my rails app into an IdP (the rails app will also act as the SP). I'm struggling to get the request validated. If I skip the validate_saml_request method, I can get both a request to the IdP side and a response to the SP side.

My configuration inside the saml_idp.rb file is below:
`service_providers = {`
 ` "http://lvh.me:3000/saml/auth" => {`
   ` fingerprint: ENV['SAML_CERT_FINGERPRINT'],`
    `metadata_url: "http://lvh.me:3000/saml/metadata",`
   `response_hosts: ["lvh.me:3000"]`
  `},`
`}`

I checked if the request is valid and get the following:
`[ ] compare to lvh.me
No acceptable AssertionConsumerServiceURL, either configure them via config.service_provider.response_hosts or match to your metadata_url host
`
There is metadata at the metadata_url as well, so not quite sure why it's not validating or loading any acceptable response hosts. Thank you!

**Comment by Zogoo** [comment]
@linda-le1 I'm not sure why your "response_hosts" return empty array in the error log. But, can you try with `response_hosts: ["lvh.me"]` on your service_providers. 
And if you have more questions you may want to ask it on our gitter room. https://gitter.im/saml_idp/community.

**Comment by linda-le1** [comment]
I made the suggested changes to the original configuration I was working with and didn't have much luck - got the same error message. I'll only have 1 SP though, so setting the config up as a single lambda function worked perfectly - thank you so much @Zogoo!
