### ISSUE TITLE
 undefined method `acs_url' for nil:NilClass

### ISSUE THREAD

**Issue by roy-li-instacart** [saml-idp/saml_idp#160]
Hi,

I'm running into an issue where in production, when calling `encode_response <my principal>` without passing any `opts` https://github.com/saml-idp/saml_idp/blob/861e67d1ed648a5fbdd41ead2941dd0e4e2ef071/lib/saml_idp/controller.rb#L92 , **occasionally** , it will throw an exception ` undefined method 'acs_url' for nil:NilClass`

After diving into the code, I found that `service_provider` might be `nil` https://github.com/saml-idp/saml_idp/blob/master/lib/saml_idp/request.rb#L63 in this case.

This is an SP-initiated workflow. I copied the `raw_saml_request` from the traceback in production and passed it to `decode_request` https://github.com/saml-idp/saml_idp/blob/861e67d1ed648a5fbdd41ead2941dd0e4e2ef071/lib/saml_idp/controller.rb#L45, then called `encode_response <my principal>` and it worked locally without any problem

Do you have any idea or suggestion for what I can debug next? Should I simply add a retry hoping that this is just a timing issue? Any help or suggestions are appreciated, thanks!

**Comment by Zogoo** [comment]
@roy-li-instacart, README might make you get confused. 
I understand correctly about your issue.
It seems like your request cannot find your service provider configuration from your service finder lambda.
From following example "some-issuer-url.com/saml" must be unique and used as key of hash. I would suggest that  you might need to check your "SP acs url" match this key during request.

Example with metadata from url. To aware it's a just example.
```ruby
  service_providers = {
    "some-issuer-url.com/saml" => {
      fingerprint: "9E:65:2E:03:06:8D:80:F2:86:C7:6C:77:A1:D9:14:97:0A:4D:F4:4D",
      metadata_url: "http://some-issuer-url.com/saml/metadata",

      # We now validate AssertionConsumerServiceURL will match the MetadataURL set above.
      # *If* it's not going to match your Metadata URL's Host, then set this so we can validate the host using this list
      response_hosts: ["foo.some-issuer-url.com"]
    },
  }
```
# Example with constant values is more practical way to setup.
```ruby
  service_providers = {
    "sp_acs_url" => {
      fingerprint: "9E:65:2E:03:06:8D:80:F2:86:C7:6C:77:A1:D9:14:97:0A:4D:F4:4D",
      acs_url: "sp_acs_url",
      cert: "PEM format certificate",
      response_hosts: ["foo.some-issuer-url.com"]
    },
  }
```
Or if you want to make sure it you also can try with lambda function directly for your service finder config.
Personally I would suggest that setup required information from SP metadata for your IdP config. 
In that case your don't really need to make sure hash key for service provider match your service provider config.
For example:
```ruby
  # You can parse your SP metadata in some where before process request
  sp_metadata = SamlIdp::IncomingMetadata.new(sp_raw_metadata)
  # In Saml config you can re-use SP metadata configs which is more accurate and dynamic rather than you setup it manually. 
  config.service_provider.finder =  lambda { |_issuer_or_entity_id|
          {
            response_hosts: sp_metadata.assertion_consumer_services.map do |acs|
              url = acs['location'] || acs[:location]
              URI(url).host
            end,
            acs_url: sp_metadata&.assertion_consumer_services&.first[:location],
            cert: sp_metadata&.signing_certificate,
            # You can calculate also finger print from SP metadata certificate. 
            # fingerprint_from_sp_metadata is sample function which uses Digest::SHA1.hexdigest
            fingerprint: fingerprint_from_sp_metadata(sp_metadata&.signing_certificate)
          }
   }
```

**Comment by roy-li-instacart** [comment]
Thank you so much for the help Zogoo!

I see. To make sure I understand, you are saying that the `metadata_url` configured in `IDP` (in this case, our company's dashboard) and the one configured in `SP` (the vendor we want the user to get access to) are different.

Due to that, the `service_provider` evaluated to `nil`, right?

If that's true, do you happen to have any idea why this error only occasionally happen? Thanks!

**Comment by Zogoo** [comment]
@roy-li-instacart I'm not sure about your implementation. If you have a single SP, that SP must have SP metadata which is XML file or string. I was calling that file "sp_raw_metadata". And I think you don't need to download SP metadata for each SAML request. Most cases "SP metadata" must be persisted in your IdP application.

**Comment by roy-li-instacart** [comment]
Hi @Zogoo so sorry for the late reply! Thanks again for the help! : )

**Comment by Zogoo** [comment]
@roy-li-instacart  let me close this issue. If you think your issue is GEM bug, please feel free to reopen this ticket.

**Comment by roy-li-instacart** [comment]
Sure, thanks again!
