### ISSUE TITLE
Fixe typo of example SamlIdpController

### ISSUE THREAD

**Issue by taketo1113** [saml-idp/saml_idp#166]
I have fixed typo for wiki page of Rails_Integration.
I replaced `found_user` to `person`, because the variable of `found_user` is not difeined in idp_make_saml_response method.

- wiki: Rails_Integration page
https://github.com/saml-idp/saml_idp/wiki/Rails_Integration

- diff
https://github.com/saml-idp/saml_idp/wiki/Rails_Integration/_compare/60f46e742a086fc2d1015e2cd6bef458f20eaa70...8d51ebaa10f9b9f71d2c0cfc94eb0eb5cf194c91

And, It can change the wiki page via not collaborator users.
Is it expected setting?

If you not allowed not collaborator users to edit page, check bellow settings.

- Changing access permissions for wikis - GitHub Doc
https://docs.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

**Comment by Zogoo** [comment]
@jphenow you may want to check "permission" of WIKI page.

**Comment by jphenow** [comment]
Thanks for the heads up folks! Disabled public edits, but also thanks for _these_ edits :D
