### ISSUE TITLE
'Signature is invalid' error when logging out

### ISSUE THREAD

**Issue by thanos982** [saml-idp/saml_idp#167]
I'm trying to get logging out to work and I get a `Signature invalid` error.

There is a signature in the XML of the service provider metadata, but the XML file doesn't seem to be loaded at all.
This is relevant to Issue #71 where the metadata persister is never called, hence the settings are never cached.

I tried to fix this manually but I run into several issues, mainly to do with the metadata_persister example method that's provided in the config file:
- `File.open Rails.root.join("cache/saml/metadata/#{fname}"), "wb"` throws an error about the file being non existent
- `settings.to_h` (where settings is an IncomingMetadata object) throws an error too.

Is there any workaround to this? How did anyone else get logging out to work?

**Comment by Zogoo** [comment]
@thanos982 
Thanks for your cooperation for this gem. I need to clarify what is your expected result.
I understand that following situation from your description, If you think I have misunderstanding, please feel free to fix.
1. You have XML metadata file of SP.
2. And you are trying todo SLO (single logout).
3. And you already have SP configuration like mentioned in our README and Wiki.
And you are expecting that load your XML file and configure SP config for your SP service?

If it's possible can you share with us your SP config hash in here. I think if you do mask for  your secret information might allow you or your team to share your SP config in here.

**Comment by thanos982** [comment]
Thank you Zogoo.

I;m still not sure how and when the metadata_persister method used but I figured out that the URL of the metadata file in my SP config was wrong, that's why I couldn't get it to work.

**Comment by Zogoo** [comment]
@thanos982 
Personally, I will not suggest to use SP metadata persister if your SP is a 3rd party service or communication is over internet.
Or also your SP doesn't change  the metadata content so often. 
Because, SP metadata content from URL might be dangerous  especially if your SP metadata URL not protected any authentication.
I would suggest to use RAW xml data and parse with `SamlIdp::IncomingMetadata.new(sp_raw_metadata)`.
