### ISSUE TITLE
Validate Signature for the SP by default

### ISSUE THREAD

**Issue by cody2094** [saml-idp/saml_idp#171]
It seems to me as though the SP's fingerprint is not validated by default although the documentation implies that the fingerprint configuration should be required. I discovered this only because I realized I forgot to change a fingerprint for one of my use cases but yet the connection still worked. 

Based on the following line of code, it seems as though the fingerprint won't be checked against the SP unless the SP is configured with an attribute of `validate_signature` that is set to something truthy. Am I right here or am I missing something?
Line of code in question: https://github.com/saml-idp/saml_idp/blob/b34adcb4edbc25eecdf4cffe71fb6b852889824f/lib/saml_idp/service_provider.rb#L25

Is this an intended design or something that was missed?

**Comment by Zogoo** [comment]
Validation of metadata signature is optional, mostly SP metadata downloaded by people who, trusting that SP metadata and uploading manually to the IdP. 
Also, there could be scenarios that the metadata doesn't have any certificate in this case if we check it by default it would break these IdP applications.

About your scenario, it might be good if you generate a fingerprint of the public key, then you don't need to change it by manually. 
This function might help you. `lib/saml_idp/fingerprint.rb`

**Comment by Zogoo** [comment]
@cody2094  we haven't heard anything from you. If you have more questions ,please feel free to open this issue.
