### ISSUE TITLE
NoMethodError in SamlIdpController#create

### ISSUE THREAD

**Issue by habin201291** [saml-idp/saml_idp#196]
Hi, I am using **Rails v7.0.8**, **Ruby v3.2.2**, **saml_idp v0.15.0** with **Devise gem v4.9.3** and I am getting an error at the line `encode_response person` that I cannot resolve. Also, the **person** object is a **current_user** i got it after ran **authenticate_user** function of Devise gem.
`NoMethodError in SamlIdpController#create`
`undefined method `[]' for nil:NilClass`

My code:
`
class SamlIdpController < ApplicationController
    include SamlIdp::Controller
    
    protect_from_forgery

    before_action :authenticate_user!, only: [:new, :create, :logout]

    def new
      render template: "saml_idp/idp/new"
    end

    def show
      render xml: SamlIdp.metadata.signed
    end

    def create
      if user_signed_in?
        # renderin xml response in saml format for devise's current_user
        @saml_response = idp_make_saml_response(current_user)
        render :template => "saml_idp/idp/saml_post", :layout => false
        return
      else
        render :template => "saml_idp/idp/new"
      end
    end

    def logout
      idp_logout
      @saml_response = idp_make_saml_response(nil)
      render :template => "saml_idp/idp/saml_post", :layout => false
    end

    def idp_logout
      user = User.find_by_email(saml_request.name_id)
      user.logout
    end
    private :idp_logout

    def idp_make_saml_response(person)
      encode_response person
    end
    protected :idp_make_saml_response
end
`

I have tried to fix it by storing Session storage in Database instead of Cookies but it still does not work. If I follow this guide How to integrate with Rails application without Devise gem, everything works fine.

Need to help!

Additionally, when I config x509_certificate and secret_key in Saml config file, I get this error below.
`OpenSSL::PKey::RSAError in SamlIdpController#show`
`Neither PUB key nor PRIV key: unsupported`
I created them with this command: **openssl req -x509 -sha256 -nodes -days 3650 -newkey rsa:2048 -keyout myKey.key -out myCert.crt**

**Comment by zorar4ik** [comment]
@habin201291 hi, have you solved this in your project? I am facing same issue, I have no idea where to dig. Seems like problems in configuration but I do not where

**Comment by Zogoo** [comment]
@zorar4ik 
Can you check your configuration with the following docs?
1. https://github.com/saml-idp/saml_idp/wiki/IdP_Configuration
2. https://github.com/saml-idp/saml_idp/wiki/Rails_Integration

**Comment by zorar4ik** [comment]
@Zogoo Yeah, I have followed both guides but I still struggle with configurations. I do not know is it because I don't understand flow properly, or because I have non-standard config. For instance I have only one provider, so I decided to use lambda for service provider configuration:
```
  config.service_provider.finder = lambda { |_issuer_or_entity_id|
    {
      fingerprint: fingerprint of generated x509 certificate,
      metadata_url: as i understand here should be url of Service Provider metadata url? it should be `service-provider.com/saml/metadata`,
      response_hosts: ["service-provider.com"]
    }
  }
  ```

**Comment by Zogoo** [comment]
@zorar4ik can you share your exact error message or backtrace with the new issue?

About your service provider, it should work if you want to put only one SP.

Here is an example of an SP provider.  `sp_metadata` is parsed SP metadata.

```ruby
    lambda { |_issuer_or_entity_id|
      {
        response_hosts: sp_metadata.assertion_consumer_services.map do |acs|
          url = acs['location'] || acs[:location]
          URI(url).host
        end,
        acs_url: sp_metadata.acs_urls.first[:location],
        cert: (sp_metadata&.signing_certificate.present? ? Base64.decode64(sp_metadata&.signing_certificate) : nil),
        fingerprint: (sp_metadata&.signing_certificate.present? ? SamlIdp::Fingerprint.certificate_digest(Base64.decode64(sp_metadata&.signing_certificate)) : nil)
      }
    }
 ```

**Comment by zorar4ik** [comment]
@Zogoo thanks for response. I suspect that I have problem with SP metadata url. 
I wanted to ask maybe it is stupid question, is it possible to get SP metadata url from request? It may seem weird but my SP can't tell me their metadata url
