### ISSUE TITLE
403 error with SLO request

### ISSUE THREAD

**Issue by habin201291** [saml-idp/saml_idp#197]
- I'm using devise_saml_authenticatable gem as Saml SP. When a logout request is sent to the IDP, the system reports error 403 as below:
`Access to localhost was denied
You don't have authorization to view this page.
HTTP ERROR 403`

- I have parsed the SLO request to XML as follows:
`<samlp:LogoutRequest Destination='http://localhost:3000/saml/logout' ID='_6e0db0f1-07a6-4814-8056-c2692d0afdf8' IssueInstant='2023-11-22T11:07:54Z' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'><saml:Issuer>http://localhost:8080/users/saml/metadata</saml:Issuer><saml:NameID Format='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'>habin201291@yopmail.com</saml:NameID><samlp:SessionIndex>_c988ca79-a95b-4c16-aa7c-5d511546afa8</samlp:SessionIndex></samlp:LogoutRequest>`

- Or  like this:
`<samlp:LogoutRequest Destination='http://localhost:3000/saml/logout' ID='_13858cfe-d248-4818-8066-e6a46db13360' IssueInstant='2023-11-24T08:42:48Z' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'><saml:Issuer>http://localhost:8080/users/saml/metadata</saml:Issuer><saml:NameID Format='urn:oasis:names:tc:SAML:2.0:nameid-format:transient'>_db03ee7c-470c-4b43-9b22-b9a0e83f61a7</saml:NameID></samlp:LogoutRequest>`

- `valid_saml_request?` function return false with error message `Signature is invalid`

- Have I made a mistake or missed something?

**Comment by Zogoo** [comment]
@habin201291 is your logout request signed? or just plain request as you described?

**Comment by Zogoo** [comment]
@habin201291 sorry for the delayed response. I think you are missing a service provider finder in your config.
In there, you need to configure the following parameters.
Here is an example of a single SP.
Following lambda should be set into your config `config.service_provider.finder = <service_providers_lambda>`
```ruby
    lambda { |_issuer_or_entity_id|
      {
        response_hosts: sp_metadata.assertion_consumer_services.map do |acs|
          url = acs['location'] || acs[:location]
          URI(url).host
        end,
        acs_url: sp_metadata.acs_urls.first[:location],
        cert: (sp_metadata&.signing_certificate.present? ? Base64.decode64(sp_metadata&.signing_certificate) : nil),
        fingerprint: (sp_metadata&.signing_certificate.present? ? SamlIdp::Fingerprint.certificate_digest(Base64.decode64(sp_metadata&.signing_certificate)) : nil)
      }
    }
 ```

**Comment by Zogoo** [comment]
So, I'm going to close this issue, if you still having trouble with your config please feel free re-open it.
