### ISSUE TITLE
what should be the configuration of service_providers in saml_config.rb 

### ISSUE THREAD

**Issue by q3tech1234** [saml-idp/saml_idp#67]
The cert is nil while debugging the `saml_request.service_provider.cert` I think this is a configuration issue please tell me what to write in the configuration for service_providers section.

**Comment by mvastola** [comment]
Just ran into this myself today. In `README.md`, when you see:
```ruby
service_providers = {
    "some-issuer-url.com/saml" => {
      fingerprint: "9E:65:2E:03:06:8D:80:F2:86:C7:6C:77:A1:D9:14:97:0A:4D:F4:4D",
      metadata_url: "http://some-issuer-url.com/saml/metadata"
    },
  }
```
You want to change that to:
```ruby
service_providers = {
    "some-issuer-url.com/saml" => {
      cert: OpenSSL::X509::Certificate.new(File.read(Rails.root.join('config', 'saml_sp.pem')))
      fingerprint: "9E:65:2E:03:06:8D:80:F2:86:C7:6C:77:A1:D9:14:97:0A:4D:F4:4D",
      metadata_url: "http://some-issuer-url.com/saml/metadata"
    },
  }
```
.. replace that path with the path to the public cert for your Service Provider, as necessary. (If you really needed, It should also be possible to obtain the cert dynamically via [this sourcery](https://stackoverflow.com/questions/34601260/using-ruby-openssl-to-download-and-read-certificates),  in which case I'd loop through the `service_providers` after setting the hash to merge in that key.)

Note you have to prepend:
```ruby
require 'openssl'
```
.. to the top of your initializer if you get the error that `OpenSSL` is not defined.

**Comment by mvastola** [comment]
Er. Disregard what I just crossed out. That's a horrible idea, security-wise. I can't believe I just suggested it.

**Comment by toasterlovin** [comment]
I'll just add in here that, if you're following the `ruby-saml` gem documentation (speaking specifically of the `issuer` setting), then the key for the service provider may need to specify the protocol. So, you may need `http://some-issuer-url.com/saml`, rather than just `some-issuer-url.com/saml`.

**Comment by jackiejohnston** [comment]
Is the service providers public cert used for signing SAML requests (as opposed to their SSL cert)? Is the fingerprint for this same cert? Is it possible to set up for a service provider that does not "sign" their SAML request with a cert/fingerprint?

**Comment by jphenow** [comment]
Cleaning up old issues. I'm assuming folks here figured out what they needed (or have moved on). If that's incorrect reopen this and we'll continue the discussion.
