### ISSUE TITLE
Via this gem, what would be the Entity ID URL, and the Single Sign On Service Endpoint URL?

### ISSUE THREAD

**Issue by gotoAndBliss** [saml-idp/saml_idp#83]
Fantastic gem here. Great work all around.

I have an SP that requires these two fields 

```
Entity ID URL
Single Sign On Service Endpoint URL
```

But I'm not entirely sure what those would be relative to the routes established.

My best guess is the `/saml/auth` for both?

**Comment by alxx** [comment]
It's a good idea to provide an answer to your own question even if you're going to close the ticket. I still can't figure out the endpoint URL, and using /saml/auth doesn't work because "Unable to find service provider for issuer" which leaves me wondering how I specify the issuer...
