### ISSUE TITLE
No way to declare a HTTP-POST SingleSignOnService

### ISSUE THREAD

**Issue by jnardone** [saml-idp/saml_idp#90]
There seems to be no way to declare a HTTP-POST binding for SingleSignOnService.

Furthermore, the confusingly-named config item `single_service_post_location` appears to be used as the location for the `HTTP-Redirect` binding for SingleSignOnService...

**Comment by mjobin-mdsol** [comment]
Pull request is ready for 18 months. we shall be reviewing and include in a release

**Comment by mjobin-mdsol** [comment]
#120 got merged for this, can you test again with v0.11.0 ?

**Comment by Zogoo** [comment]
@jnardone I hope your reported issue is already fixed in our latest release. If you still get the same issue, could you please reopen this issue.
