### ISSUE TITLE
Update ruby-saml gem dependency to 1.7 to patch new SAML vulnerability.

### ISSUE THREAD

**Issue by ranierorusso** [saml-idp/saml_idp#91]
OneLogin just alerted its users to a new SAML vulnerability. They have already patched their ruby-saml gem in version 1.7 and this gem should now be referencing that version (https://github.com/saml-idp/saml_idp/blob/5a1345eb457b9149f5c6e7343254ebe344643521/saml_idp.gemspec#L54). 

Here's the patch in onelogin/ruby-saml: https://github.com/onelogin/ruby-saml/commit/048a544730930f86e46804387a6b6fad50d8176f

I can open a PR for this change if you'd like but hopefully this can get patched as soon as possible!

Thank you.

**Comment by jnardone** [comment]
I don't believe Onelogin's gem is used in the library code, just the unit tests.

That said, it's unclear to me whether the implementation of this library has a similar vulnerability in its XML handling.
