### ISSUE TITLE
inline script fails with csp

### ISSUE THREAD

**Issue by mkamensky** [saml-idp/saml_idp#95]
Hi,

The view file `saml_post.html.erb` contains inline javascript: https://github.com/saml-idp/saml_idp/blob/5a1345eb457b9149f5c6e7343254ebe344643521/app/views/saml_idp/idp/saml_post.html.erb#L7 
This is blocked by content security policy, if set

Thanks

**Comment by chrislewis60** [comment]
I've just been caught by this as well. Another solution to this is to update your Content Security Policy form_action to allow the Service Provider hosts that you've added to your IdP config. For example, we're using the secure headers gem, and our CSP config now looks like this: 

```
config.csp = {
    ...
    form_action: %w['self' service_provider1.domain.com service_provider2.domain.com],
} 
```
I might put in a pull request which is just a couple of lines of comments in the SamlIdp config file, at the point where service provider respose_hosts are configured, just to warn people that if they are using a CSP they need to configure it correctly for the service provider hosts you're using.

**Comment by Zogoo** [comment]
I'm closing this issue. Because, gem no longer supporting HTML views by default. You can create own view in your rails app and fully manage everything in your app side.
