### ISSUE TITLE
saml/metadata endpoint generates <script/> tag

### ISSUE THREAD

**Issue by beniutek** [saml-idp/saml_idp#96]
Hi

When I go to the `saml/metadata` endpoint of my identity provider I see the generated metadata, and it starts like this:

```
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" ID="_01fe34f0-60ff-0136-f794-745c89be5ec5" entityID="http://localhost:3030/saml">
<script/>
<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
...more xml

```

why `<script />` is being generated? When I try to validate this (ie. on
[saml tool](https://www.samltool.com/validate_xml.php))

then it's not being validated correctly. Additionally, when I try to register my identity provider with a service provider that I'm supposed to use (third part app) I can't because of the metadata being not correct (checked that, because I have manually generated metadata based on the saml tool above and was able to register my identity provider)

Has anyone had similar issues?

**Comment by jphenow** [comment]
Hey sorry, trying to get back to this project a bit. Could you share some of your configuration (redact keys, etc.)? I don't know of any way we'd be generating a script tag in the code

**Comment by beniutek** [comment]
Hey, 

So I was copying the generated metadata from the browser (chrome)

But when I used the metadata builder in the console the generated metadata was without the script tag.

I can only assume it was my browser adding this in the process of rendering the xml

Why? Dunno

But this is a non issue, sorry!

**Comment by jphenow** [comment]
No problem! Glad you got it straightened out!
